name: Star

on:
  watch:
    types: [started]

jobs:
 star:
   runs-on: ubuntu-latest
   steps:
   - uses: 8398a7/action-slack@v3
     with:
       status: ${{ job.status }}
       fields: repo
       text: "☆ from https://github.com/${{ github.event.sender.login }}, Total: ${{ github.event.repository.stargazers_count }}"
     env:
       SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
